import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Jenni',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Brian',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Cornish Mug',
      category: 'China',
      image: '/images/p1.jpg',
      price: 12,
      countInStock: 10,
      brand: 'Mug',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: '3 Jars',
      category: 'China',
      image: '/images/p2.jpg',
      price: 10,
      countInStock: 20,
      brand: 'Cornish',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Glass heart',
      category: 'Glass',
      image: '/images/p3.jpg',
      price: 15.5,
      countInStock: 0,
      brand: 'Cornish Glass',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Cornish Gin',
      category: 'Alcahol',
      image: '/images/p4.jpg',
      price: 18,
      countInStock: 15,
      brand: 'Gin',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Pixie',
      category: 'Art',
      image: '/images/p5.jpg',
      price: 8.5,
      countInStock: 5,
      brand: 'Cornish Art',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Wizard statue',
      category: 'Art',
      image: '/images/p6.jpg',
      price: 12.5,
      countInStock: 12,
      brand: 'Celtic',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
